/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.AtividadeDAO;
import DAO.CursoDAO;
import DAO.TipoAtividadeDAO;
import Model.Atividade;
import Model.Curso;
import Model.TipoAtividade;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author ALUNOS
 */
public class GUICadTipoAtividade extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICadTipoAtividade
     */
    public GUICadTipoAtividade() {
        initComponents();
        
        CursoDAO cursoDAO = new CursoDAO();
        ArrayList<Curso> cursos = cursoDAO.retrieveAll();
        
        jcCurso.addItem("Selecione");
        for (Curso curso : cursos) {
            jcCurso.addItem(curso);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtLimiteHoras = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtDescricao = new javax.swing.JTextArea();
        jbCadastrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcCurso = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Cadastro de Atividades");

        jLabel1.setText("Código");

        jLabel2.setText("Limite de horas");

        jLabel3.setText("Descrição");

        jtDescricao.setColumns(20);
        jtDescricao.setRows(5);
        jScrollPane1.setViewportView(jtDescricao);

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Curso");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(jtLimiteHoras)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 359, Short.MAX_VALUE))
                    .addComponent(jcCurso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtLimiteHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        try {
            Curso curso = (Curso) jcCurso.getSelectedItem();
        
            TipoAtividade tipoAtividade = new TipoAtividade();
            tipoAtividade.setLimiteHoras(Integer.parseInt(jtLimiteHoras.getText()));
            tipoAtividade.setDescricao(jtDescricao.getText());

            TipoAtividadeDAO taDAO = new TipoAtividadeDAO();
            int idTipoAtividade = taDAO.persist(tipoAtividade);

            tipoAtividade.setId(idTipoAtividade);

            Atividade atividade = new Atividade();
            atividade.setCodigo(Integer.parseInt(jtCodigo.getText()));
            atividade.setCurso(curso);
            atividade.setTipoAtividade(tipoAtividade);

            AtividadeDAO aDAO = new AtividadeDAO();
            aDAO.persist(atividade);

            jcCurso.setSelectedIndex(0);
            jtLimiteHoras.setText("");
            jtDescricao.setText("");
            jtCodigo.setText("");

            JOptionPane.showMessageDialog(
                this, 
                "Cadastro realizado com sucesso!", 
                "Sucesso", 
                JOptionPane.INFORMATION_MESSAGE
            );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this, 
                "Erro ao cadastrar!", 
                "Erro", 
                JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JComboBox jcCurso;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextArea jtDescricao;
    private javax.swing.JTextField jtLimiteHoras;
    // End of variables declaration//GEN-END:variables
}
